[package]
name = "sfs_rpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.9.0"
tonic = { version = "0.6.2", features = ["tls"]}

[build-dependencies]
tonic-build = "0.6.2"
