[package]
name = "sfs_rpc"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "*"
grpcio = "0.10.1"
protobuf = "~2"

[build-dependencies]
protoc-grpcio = "3.0.0"
