[package]
name = "sfs_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#[lib]
#crate-type = ["staticlib"]
#name = "sfs_lib"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = '*'
#downcast-rs = '*'
lazy_static = '*'
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "*"
tokio = { version = "1.17", features = ["full"] }
tarpc = { version = "0.27", features = ["full"] }
futures = '*'
sfs_lib_server = { path = "sfs_lib_server" }
